export const CREATE_TOKEN_API = "/api/token/"
export const VERIFY_TOKEN_API = "/api/token/verify/"
export const REFRESH_TOKEN_API = "/api/token/refresh/"
export const GET_USERS_API = "/v1/tenant/users/"
export const USER_REGISTER_API = "/v1/tenant/register/"
export const USER_PROFILE_API = "/v1/tenant/user/profile/"
